# This file was generated by GoReleaser. DO NOT EDIT.
cask "specbase" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_darwin_amd64.tar.gz"
      sha256 "5b5509186db8b0a2cf1b9a44b09c7719a25c4d9972b137fa1c8c19649baf09ee"
    end
    on_arm do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_darwin_arm64.tar.gz"
      sha256 "356e30ba429563e4d53859d896a98f09bd007ff9f15b1675846c3c22d3ee3c2d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_linux_amd64.tar.gz"
      sha256 "ba9195ba16500e5f8b481348a78e2e9c8824be7cc7dd373895e73bc15ab1e1cd"
    end
    on_arm do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_linux_arm64.tar.gz"
      sha256 "e1d6d2096068cde56a45ced3c3f71847312d36799531ffa76e65c8a74ec89267"
    end
  end

  name "specbase"
  desc "The spec oracle for AI agents and developers"
  homepage "https://specbase.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specbase"

  # No zap stanza required

end
