# This file was generated by GoReleaser. DO NOT EDIT.
cask "specbase" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_darwin_amd64.tar.gz"
      sha256 "3f686073b6e47fcf8becd9fcb9baf8d89fbe03c4fa9616220a3a92890093b84a"
    end
    on_arm do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_darwin_arm64.tar.gz"
      sha256 "ff44a0f4010b91c9c488b096ffd9596a05d9bfe474f27850c2d160a4df2f2ff0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_linux_amd64.tar.gz"
      sha256 "c56208cc5cfcb2148da16b7160462f45e79ae8d334a884fd64bd02dfb2de1842"
    end
    on_arm do
      url "https://github.com/aallbrig/specbase/releases/download/v#{version}/specbase_#{version}_linux_arm64.tar.gz"
      sha256 "58941fefee4a7b475c459d42d9f6454bae9b2e2923e8d34435d3f73598810ff3"
    end
  end

  name "specbase"
  desc "The spec oracle for AI agents and developers"
  homepage "https://specbase.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specbase"

  # No zap stanza required

end
